export class PageConstants {
  private constructor() {}
  public static readonly HOME_PAGE = 'HomePage';
  public static readonly TEXT_PAGE = 'TextPage';
  public static readonly TEXT_AREA_PAGE = 'TextAreaPage';
  public static readonly TEXT_INPUT_PAGE = 'TextInput';
  public static readonly RICH_EDITOR_PAGE = 'RichEditor';
  public static readonly SEARCH_PAGE = 'Search';
  public static readonly SPAN_PAGE = 'Span';
  public static readonly IMAGE_SPAN_PAGE = 'ImageSpan';
  public static readonly CONTAINER_SPAN_PAGE = 'ContainerSpan';
  public static readonly SYMBOL_SPAN_PAGE = 'SymbolSpan';
  public static readonly SYMBOL_GLYPH_PAGE = 'SymbolGlyph';
  public static readonly HYPER_LINK_PAGE = 'Hyperlink';
  public static readonly RICH_TEXT_PAGE = 'RichText';
  public static readonly SELECTION_MENU_PAGE = 'SelectionMenu';
  public static readonly TEXT_PARMA_PAGE = '属性字符串';
  public static readonly TEXT_INTERFACE_PAGE = '文本组件公共接口';

}